services:
  postgres: 
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - senai

  reverse-proxy:
    # 
    image: traefik:v3.2
    # 
    command: --api.insecure=true --providers.docker
    ports:
      # 
      - "80:80"
      # 
      - "8080:8080"
    volumes:
      # 
      - /var/run/docker.sock:/var/run/docker.sock

  parts:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9999:9999'
    networks:
      - senai
    depends_on:
      - postgres
    volumes:
      - ./backend/apis/parts:/api
    environment:
      PYTHONPATH: /api/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parts.rule=PathPrefix(`/parts`)"
      - "traefik.http.services.parts.loadbalancer.server.port=9999"
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9999"]
  
  machines:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9998:9998'
    networks:
      - senai
    depends_on:
      - postgres
    volumes:
      - ./backend/apis/machines:/api
    environment:
      PYTHONPATH: /api/app 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.machines.rule=PathPrefix(`/machines`)"
      - "traefik.http.services.machines.loadbalancer.server.port=9998"
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9998"]

  maintenances:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9997:9997'
    networks:
      - senai
    depends_on:
      - postgres
    volumes:
      - ./backend/apis/maintenances:/api
    environment:
      PYTHONPATH: /api/app 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maintenances.rule=PathPrefix(`/maintenances`)"
      - "traefik.http.services.maintenances.loadbalancer.server.port=9997"
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9997"]

  users:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9996:9996'
    networks:
      - senai
    depends_on:
      - postgres
    volumes:
      - ./backend/apis/users:/api
    environment:
      PYTHONPATH: /api/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=PathPrefix(`/users`)"
      - "traefik.http.services.users.loadbalancer.server.port=9996" 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9996"]

networks:
  senai:
    driver: bridge

volumes:
  postgres_data:
