services:
  postgres: 
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - senai

  parts:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9999:9999'
    networks:
      - senai
    depends_on:
      - postgres
    volumes:
      - ./backend/apis/parts:/api
    environment:
      PYTHONPATH: /api/app
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9999"]
  
  machines:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9998:9998'
    networks:
      - senai
    depends_on:
      - postgres
    volumes:
      - ./backend/apis/machines:/api
    environment:
      PYTHONPATH: /api/app 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9998"]

  maintenances:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9997:9997'
    networks:
      - senai
    depends_on:
      - postgres
    volumes:
      - ./backend/apis/maintenances:/api
    environment:
      PYTHONPATH: /api/app 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9997"]

  users:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9996:9996'
    networks:
      - senai
    depends_on:
      - postgres
    volumes:
      - ./backend/apis/users:/api
    environment:
      PYTHONPATH: /api/app/ 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9996"]

networks:
  senai:
    driver: bridge

volumes:
  postgres_data:
