version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB_PARTS: ${POSTGRES_DB_PARTS}
      POSTGRES_DB_MACHINES: ${POSTGRES_DB_MACHINES}
      POSTGRES_DB_MAINTENANCES: ${POSTGRES_DB_MAINTENANCES}
      POSTGRES_DB_USERS: ${POSTGRES_DB_USERS}
    ports:
      - 5432:5432
      - 5433:5433
      - 5434:5434
      - 5435:5435
    volumes:
      - postgres_data_parts:/var/lib/postgresql/data
      - postgres_data_machines:/var/lib/postgresql/data
      - postgres_data_maintenances:/var/lib/postgresql/data
      - postgres_data_users:/var/lib/postgresql/data
    networks:
      - senai_parts
      - senai_machines
      - senai_maintenances
      - senai_users

  networks:
    senai_parts:
    senai_machines:
    senai_maintenances:
    senai_users:

  volumes:
    postgres_data_parts:
    postgres_data_machines:
    postgres_data_maintenances:
    postgres_data_users:

  parts:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9999:9999'
    networks:
      - senai_parts
    depends_on:
      - postgres_parts
    volumes:
      - ./backend/apis/parts:/api
    environment:
      PYTHONPATH: /api/app
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9999"]

  machines:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9998:9998'
    networks:
      - senai_machines
    depends_on:
      - postgres_machines
    volumes:
      - ./backend/apis/machines:/api
    environment:
      PYTHONPATH: /api/app 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9998"]

  maintenances:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9997:9997'
    networks:
      - senai_maintenances
    depends_on:
      - postgres_maintenances
    volumes:
      - ./backend/apis/maintenances:/api
    environment:
      PYTHONPATH: /api/app 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9997"]

  users:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9996:9996'
    networks:
      - senai_users
    depends_on:
      - postgres_users
    volumes:
      - ./backend/apis/users:/api
    environment:
      PYTHONPATH: /api/app 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9996"]