version: '3'

services:
  postgres_parts:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PARTS}
    ports:
      - 5433:5433
    volumes:
      - postgres_data_parts:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - senai_parts

  postgres_machines:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_MACHINES}
    ports:
      - 5434:5434
    volumes:
      - postgres_data_machines:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - senai_machines

  postgres_maintenances:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_MAINTENANCES}
    ports:
      - 5435:5435
    volumes:
      - postgres_data_maintenances:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - senai_maintenances

  postgres_users:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USERS}
    ports:
      - 5436:5436
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - senai_users

  parts:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9999:9999'
    networks:
      - senai_parts
    depends_on:
      - postgres_parts
    volumes:
      - ./backend/apis/parts:/api
    environment:
      PYTHONPATH: /api/app
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9999"]

  machines:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9998:9998'
    networks:
      - senai_machines
    depends_on:
      - postgres_machines
    volumes:
      - ./backend/apis/machines:/api
    environment:
      PYTHONPATH: /api/app 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9998"]

  maintenances:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9997:9997'
    networks:
      - senai_maintenances
    depends_on:
      - postgres_maintenances
    volumes:
      - ./backend/apis/maintenances:/api
    environment:
      PYTHONPATH: /api/app 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9997"]

  users:
    build: ./backend/
    env_file:
      - .env
    ports: 
      - '9996:9996'
    networks:
      - senai_users
    depends_on:
      - postgres_users
    volumes:
      - ./backend/apis/users:/api
    environment:
      PYTHONPATH: /api/app 
    command: ["poetry", "run", "fastapi", "run", "api/app/main.py", "--port", "9996"]

volumes:
  postgres_data_parts:
  postgres_data_machines:
  postgres_data_maintenances:
  postgres_data_users:

networks:
  senai_parts:
  senai_machines:
  senai_maintenances:
  senai_users: