-- Cria as bases de dados e as tabelas necessárias
CREATE DATABASE ${POSTGRES_DB_PARTS};
CREATE DATABASE ${POSTGRES_DB_MACHINES};
CREATE DATABASE ${POSTGRES_DB_MAINTENANCES};
CREATE DATABASE ${POSTGRES_DB_USERS};

-- Cria as tabelas nas bases de dados
\c ${POSTGRES_DB_PARTS}
CREATE TABLE IF NOT EXISTS parts (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  quantity INT NOT NULL
);

\c ${POSTGRES_DB_MACHINES}
CREATE TABLE IF NOT EXISTS machines (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  quantity INT NOT NULL
);

\c ${POSTGRES_DB_MAINTENANCES}
CREATE TABLE IF NOT EXISTS maintenances (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  quantity INT NOT NULL
);

\c ${POSTGRES_DB_USERS}
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);