FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && apt-get clean

ENV PATH="/root/.local/bin:$PATH"

COPY pyproject.toml ./
RUN poetry install --no-root --no-dev && poetry cache clear --all pypi