# Use a imagem oficial do Python como base
FROM python:3.10-slim-buster

# Definir o diretório de trabalho
WORKDIR /app

# Instalar as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código-fonte para o contêiner
COPY . .

# Definir o comando padrão para iniciar a aplicação
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]